In [134]:
import numpy as np
import sympy as sym

n = 20

def Polinomios_Laguerre(n):
  x = sym.Symbol('x')
  a = sym.exp(x)/sym.factorial(n)
  diferencial = (sym.exp(-x)*(x**n))
  
  for i in range(n):
    diferencial = sym.diff(diferencial)
  return sym.simplify(a*diferencial)
    
    
Polinomios = []
for i in range(n):
    Polinomios.append(Polinomios_Laguerre(i))

print(Polinomios)

[1, 1 - x, x**2/2 - 2*x + 1, -x**3/6 + 3*x**2/2 - 3*x + 1, x**4/24 - 2*x**3/3 + 3*x**2 - 4*x + 1, -x**5/120 + 5*x**4/24 - 5*x**3/3 + 5*x**2 - 5*x + 1, x**6/720 - x**5/20 + 5*x**4/8 - 10*x**3/3 + 15*x**2/2 - 6*x + 1, -x**7/5040 + 7*x**6/720 - 7*x**5/40 + 35*x**4/24 - 35*x**3/6 + 21*x**2/2 - 7*x + 1, x**8/40320 - x**7/630 + 7*x**6/180 - 7*x**5/15 + 35*x**4/12 - 28*x**3/3 + 14*x**2 - 8*x + 1, -x**9/362880 + x**8/4480 - x**7/140 + 7*x**6/60 - 21*x**5/20 + 21*x**4/4 - 14*x**3 + 18*x**2 - 9*x + 1, x**10/3628800 - x**9/36288 + x**8/896 - x**7/42 + 7*x**6/24 - 21*x**5/10 + 35*x**4/4 - 20*x**3 + 45*x**2/2 - 10*x + 1, -x**11/39916800 + 11*x**10/3628800 - 11*x**9/72576 + 11*x**8/2688 - 11*x**7/168 + 77*x**6/120 - 77*x**5/20 + 55*x**4/4 - 55*x**3/2 + 55*x**2/2 - 11*x + 1, x**12/479001600 - x**11/3326400 + 11*x**10/604800 - 11*x**9/18144 + 11*x**8/896 - 11*x**7/70 + 77*x**6/60 - 33*x**5/5 + 165*x**4/8 - 110*x**3/3 + 33*x**2 - 12*x + 1, -x**13/6227020800 + 13*x**12/479001600 - 13*x**11/6652800 + 143

In [156]:
x = sym.Symbol('x')

def GetNewtonRaphson(f,df,xn,itmax = 100, precision=1e-5):
    error = 1
    it = 0
    while error > precision and it <= itmax:
        try:
            xn1 = xn - f(xn)/df(xn)
            error = np.abs(f(xn)/df(xn))  
        except ZeroDivisionError:
            print('Division por cero')
        it += 1
        xn = xn1
    if it == itmax:
        False
    else:
        return xn
    
def GetAllRoots(f,df,x,tolerancia=8):
    
    Roots = np.array([])
    
    for i in x:
        
        root = GetNewtonRaphson(f,df,i)
        
        if root != False:
            
            croot = np.round(root, tolerancia)
            
            if croot not in Roots:
                Roots = np.append(Roots,croot)
                
    Roots.sort()
        
    return Roots


xj = np.linspace(0,100)

roots = []

for i in Polinomios[1:]:
    f = sym.lambdify(x,i)
    df = sym.lambdify(x,sym.diff(i))
    roots.append(GetAllRoots(f,df,xj))

roots

[array([1.]),
 array([0.58578644, 3.41421356]),
 array([0.41577456, 2.29428036, 6.28994508]),
 array([0.32254769, 1.7457611 , 4.5366203 , 9.39507091]),
 array([ 0.26356032,  1.41340306,  3.59642577,  7.08581001, 12.64080084]),
 array([ 0.2228466 ,  1.1889321 ,  2.99273633,  5.77514357,  9.83746742,
        15.98287398]),
 array([ 0.19304368,  2.56787674,  4.90035308,  8.18215344, 12.73418029,
        19.39572786]),
 array([ 0.17027963,  2.25108663,  4.26670017,  7.0459054 , 10.75851601,
        15.74067864, 22.86313174]),
 array([ 0.15232223,  2.00513516,  3.78347397,  6.20495678,  9.37298525,
        13.46623691, 18.83359779, 26.37407189]),
 array([ 0.13779347,  1.8083429 ,  3.4014337 ,  5.55249614,  8.33015275,
        11.84378584, 16.27925783, 21.99658581, 29.92069701]),
 array([ 0.12579644,  1.64715055,  5.0292844 ,  7.50988786, 10.605951  ,
        14.43161376, 19.1788574 , 25.21770934, 33.49719285]),
 array([ 0.11572212,  0.61175748,  4.59922764,  6.84452545,  9.62131684,
       